import type { Metadata } from "next";
import { NeonAuthUIProvider, UserButton } from "@neondatabase/auth/react";
import { authClient } from "@/lib/auth/client";
import Link from "next/link";
import "./globals.css"
import { getSession } from "@/lib/auth/server";
import { redirect } from "next/navigation";
import "dotenv/config"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
 

  return (
    <html
      lang="en"
      className="h-full w-full antialiased"
      suppressHydrationWarning
    >
      <body className="min-h-full w-full flex flex-col bg-black text-white font-sans">
        <NeonAuthUIProvider authClient={authClient as any} defaultTheme="dark">
          
          <header className="w-full border-b border-gray-800 bg-black/80 backdrop-blur">
            <div className="mx-auto w-full max-w-6xl flex h-16 items-center justify-between px-4">
              
              <Link href="/" className="text-sm font-semibold tracking-wide">
                Event Planner
              </Link>

              <nav className="flex items-center gap-4">
                <Link
                  href="/dashboard"
                  className="text-sm text-gray-400 hover:text-white transition"
                >
                  Dashboard
                </Link>
                <UserButton size="icon" />
              </nav>
            </div>
          </header>

          <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col px-4 py-8">
            {children}
          </main>

        </NeonAuthUIProvider>
      </body>
    </html>
  );
}